coverage:
  status:
    project:
      default:
        target: 90%    # overall coverage threshold
    patch:
      default:
        target: 90%    # patch coverage threshold
        base: auto
        # Only post patch coverage on decreases
        only_pulls: true