"""Packaging utilities for agent deployment.

Handles zipping agent code and generating entrypoints for AgentCore.
"""

import ast
import inspect
import logging
import os
from typing import TYPE_CHECKING

from ._constants import PACKAGING_EXCLUDES
from ._exceptions import DeployPackagingException

if TYPE_CHECKING:
    from ...agent.agent import Agent

logger = logging.getLogger(__name__)

AGENTCORE_WRAPPER_TEMPLATE = '''\

# --- AgentCore wrapper (auto-generated by strands deploy) ---
from bedrock_agentcore import BedrockAgentCoreApp

app = BedrockAgentCoreApp()


@app.entrypoint
def invoke(payload):
    prompt = payload.get("prompt", "Hello!")
    result = {agent_var}(prompt)
    return {{"result": str(result), "stop_reason": result.stop_reason}}


if __name__ == "__main__":
    app.run()
'''


def _find_caller_info(agent: "Agent") -> tuple[str, str, str] | None:
    """Find the source file and agent variable name from the call stack.

    Walks the stack to find the first frame outside the deploy package,
    then searches frame locals for the agent object to determine its variable name.

    Returns:
        Tuple of (source_code, agent_variable_name, caller_dir_relpath), or None if not found.
        caller_dir_relpath is the caller's directory relative to CWD (e.g., "src/strands/afarnsandbox").
    """
    deploy_package = os.path.dirname(__file__)

    for frame_info in inspect.stack():
        frame = frame_info[0]
        filename = frame.f_code.co_filename

        # Skip frames inside the deploy package itself
        if os.path.commonpath([os.path.abspath(filename), deploy_package]) == deploy_package:
            continue

        # Skip non-file sources (e.g., <stdin>, <string>)
        if not os.path.isfile(filename):
            continue

        # Find the variable name that holds the agent object
        agent_var = None
        for var_name, var_value in frame.f_locals.items():
            if var_value is agent:
                agent_var = var_name
                break

        if agent_var is None:
            continue

        try:
            with open(filename, encoding="utf-8") as f:
                source = f.read()
            # Compute the caller's directory relative to CWD
            caller_dir = os.path.relpath(os.path.dirname(os.path.abspath(filename)), os.getcwd())
            return source, agent_var, caller_dir
        except OSError:
            continue

    return None


class _DeployStripper(ast.NodeTransformer):
    """AST transformer that removes deploy-related code from the caller's source."""

    def __init__(self, agent_var: str = ""):
        self._agent_var = agent_var

    def _is_strands_deploy_call(self, node: ast.AST) -> bool:
        """Check if a node is a call to our deploy() with the agent as the first arg."""
        if not isinstance(node, ast.Call):
            return False
        func = node.func
        is_deploy_name = (isinstance(func, ast.Name) and func.id == "deploy") or (
            isinstance(func, ast.Attribute) and func.attr == "deploy"
        )
        if not is_deploy_name:
            return False
        # If we know the agent variable, verify it's the first argument
        if self._agent_var and node.args:
            first_arg = node.args[0]
            if isinstance(first_arg, ast.Name) and first_arg.id == self._agent_var:
                return True
            return False
        return True

    def visit_Expr(self, node: ast.Expr) -> ast.Expr | None:
        """Remove bare deploy(agent, ...) calls."""
        if self._is_strands_deploy_call(node.value):
            return None
        return node

    def visit_Assign(self, node: ast.Assign) -> ast.Assign | None:
        """Remove result = deploy(agent, ...) assignments."""
        if self._is_strands_deploy_call(node.value):
            return None
        return node

    def visit_ImportFrom(self, node: ast.ImportFrom) -> ast.ImportFrom | None:
        """Remove deploy imports and convert relative imports to absolute.

        Relative imports (from .foo import X) don't work in a standalone script.
        The entrypoint runs outside of any package, so we convert them to
        absolute imports (from foo import X) since all files are at the zip root.
        """
        # Remove deploy imports
        if node.module and ("strands.experimental.deploy" in node.module or node.module == "strands.experimental"):
            if node.names:
                remaining = [alias for alias in node.names if alias.name != "deploy"]
                if remaining:
                    node.names = remaining
                    return node
                return None

        # Convert relative imports to absolute
        if node.level and node.level > 0:
            node.level = 0

        return node

    def visit_If(self, node: ast.If) -> ast.If | None:
        """Remove if __name__ == '__main__' blocks."""
        if (
            isinstance(node.test, ast.Compare)
            and isinstance(node.test.left, ast.Name)
            and node.test.left.id == "__name__"
            and len(node.test.comparators) == 1
            and isinstance(node.test.comparators[0], ast.Constant)
            and node.test.comparators[0].value == "__main__"
        ):
            return None
        return node



def _strip_deploy_call(source: str, agent_var: str = "") -> str:
    """Remove deploy-related code from the caller's source.

    Removes deploy imports, the deploy(agent_var, ...) call, everything after it,
    and any if __name__ == '__main__' blocks. Also converts relative
    imports to absolute.
    """
    tree = ast.parse(source)
    stripper = _DeployStripper(agent_var)

    # First, truncate the module body at the deploy call — everything after it
    # (print statements, etc.) is deploy output code that doesn't belong in the entrypoint
    new_body = []
    for node in tree.body:
        is_deploy = False
        if isinstance(node, ast.Expr) and stripper._is_strands_deploy_call(node.value):
            is_deploy = True
        elif isinstance(node, ast.Assign) and stripper._is_strands_deploy_call(node.value):
            is_deploy = True
        if is_deploy:
            break
        new_body.append(node)
    tree.body = new_body

    # Then apply remaining transformations (deploy imports, relative imports, if __name__)
    tree = stripper.visit(tree)
    ast.fix_missing_locations(tree)
    return ast.unparse(tree)


def generate_agentcore_entrypoint(agent: "Agent") -> str:
    """Generate a BedrockAgentCoreApp entrypoint for the agent.

    Copies the caller's source file, strips the deploy() call, and appends
    the AgentCore wrapper.

    Raises:
        DeployPackagingException: If the caller's source file cannot be found.
    """
    caller_info = _find_caller_info(agent)

    if caller_info is None:
        raise DeployPackagingException(
            "Could not find the source file that called deploy(). "
            "deploy() must be called from a .py file, not a REPL or notebook."
        )

    source, agent_var, caller_dir = caller_info
    cleaned = _strip_deploy_call(source, agent_var)
    preamble = (
        '"""Auto-generated Strands Agent entrypoint for AgentCore."""\n'
        "import sys\nimport os\n\n"
        "_here = os.path.dirname(__file__)\n"
        "sys.path.insert(0, _here)\n"
    )
    # If the caller's file is in a subdirectory of CWD, add that subdir to sys.path
    # so its sibling modules (my_tools.py, etc.) are importable.
    # TODO: For large codebases with complex import hierarchies (editable installs,
    # custom PYTHONPATH), walk all parent dirs from caller_dir up to CWD and add
    # each to sys.path to cover more project layouts.
    if caller_dir and caller_dir != ".":
        preamble += f"sys.path.insert(0, os.path.join(_here, {caller_dir!r}))\n"
    preamble += "\n"
    wrapper = AGENTCORE_WRAPPER_TEMPLATE.format(agent_var=agent_var)
    return preamble + cleaned + wrapper



def _should_exclude(path: str, base_dir: str) -> bool:
    """Check if a path should be excluded from the deployment zip."""
    rel = os.path.relpath(path, base_dir)
    parts = rel.split(os.sep)
    for part in parts:
        if part in PACKAGING_EXCLUDES:
            return True
        # Match wildcard patterns like *.egg-info
        for pattern in PACKAGING_EXCLUDES:
            if pattern.startswith("*") and part.endswith(pattern[1:]):
                return True
    return False
