"""Metrics that are emitted in Strands-Agents."""

STRANDS_EVENT_LOOP_CYCLE_COUNT = "strands.event_loop.cycle_count"
STRANDS_EVENT_LOOP_START_CYCLE = "strands.event_loop.start_cycle"
STRANDS_EVENT_LOOP_END_CYCLE = "strands.event_loop.end_cycle"
STRANDS_TOOL_CALL_COUNT = "strands.tool.call_count"
STRANDS_TOOL_SUCCESS_COUNT = "strands.tool.success_count"
STRANDS_TOOL_ERROR_COUNT = "strands.tool.error_count"
# The memory metrics below are recorded with a ``store_name`` dimension. This assumes a
# small, fixed set of configured stores; creating stores per user or per session would
# make ``store_name`` high-cardinality and degrade metric exporters and backends.
STRANDS_MEMORY_SEARCH_CALL_COUNT = "strands.memory.search.call_count"
STRANDS_MEMORY_SEARCH_SUCCESS_COUNT = "strands.memory.search.success_count"
STRANDS_MEMORY_SEARCH_ERROR_COUNT = "strands.memory.search.error_count"
STRANDS_MEMORY_ADD_CALL_COUNT = "strands.memory.add.call_count"
STRANDS_MEMORY_ADD_SUCCESS_COUNT = "strands.memory.add.success_count"
STRANDS_MEMORY_ADD_ERROR_COUNT = "strands.memory.add.error_count"
STRANDS_MEMORY_EXTRACT_CALL_COUNT = "strands.memory.extract.call_count"
STRANDS_MEMORY_EXTRACT_SUCCESS_COUNT = "strands.memory.extract.success_count"
STRANDS_MEMORY_EXTRACT_ERROR_COUNT = "strands.memory.extract.error_count"
STRANDS_MEMORY_INJECT_COUNT = "strands.memory.inject.count"

# Histograms
STRANDS_EVENT_LOOP_LATENCY = "strands.event_loop.latency"
STRANDS_TOOL_DURATION = "strands.tool.duration"
STRANDS_EVENT_LOOP_CYCLE_DURATION = "strands.event_loop.cycle_duration"
STRANDS_EVENT_LOOP_INPUT_TOKENS = "strands.event_loop.input.tokens"
STRANDS_EVENT_LOOP_OUTPUT_TOKENS = "strands.event_loop.output.tokens"
STRANDS_EVENT_LOOP_CACHE_READ_INPUT_TOKENS = "strands.event_loop.cache_read.input.tokens"
STRANDS_EVENT_LOOP_CACHE_WRITE_INPUT_TOKENS = "strands.event_loop.cache_write.input.tokens"
STRANDS_MODEL_TIME_TO_FIRST_TOKEN = "strands.model.time_to_first_token"
STRANDS_MEMORY_SEARCH_DURATION = "strands.memory.search.duration"
STRANDS_MEMORY_SEARCH_RESULTS = "strands.memory.search.results"
STRANDS_MEMORY_ADD_DURATION = "strands.memory.add.duration"
STRANDS_MEMORY_EXTRACT_DURATION = "strands.memory.extract.duration"
STRANDS_MEMORY_EXTRACT_ENTRIES = "strands.memory.extract.entries"
STRANDS_MEMORY_INJECT_ENTRIES = "strands.memory.inject.entries"
