name: Dispatch Docs
on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Dispatch
        run: gh api repos/${{ github.repository_owner }}/docs/dispatches -F event_type=sdk-push
